### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by yangkuoone** [MultimediaSemantics/entity2vec#1]
Hello,
       Firstly, Thank you for your codes. I had two questions. 
       1. where is the paper about the entity2vec.
       2. There is a problem about the code.  The function simulate_walks of  node2vec,  as follows:
            last = walk[-1]
	    for entity in walk:
		if entity == last:
			walks_file.write(''.join(entity.encode('utf-8')+'\n'))
                else:
         if one walk have two same number and the last number is this number, then the  walk will be divided
         to two lines, even multi-lines.

**Comment by enricopal** [comment]
Hi yangkuoone,
thank you for your comment. 
1. we're still working on a paper
2. thanks,I'll fix it!
